
import { AeroGearConfiguration, coreInstance } from "@aerogear/core";

/**
 * Initialize all platform SDK's by using configuration generated by AeroGear command line client
 *
 * @param config object containing SDK. Object can be read from file or pasted directly in source code.
 */
export const init = function(config: AeroGearConfiguration): Promise<void> {
  return coreInstance.init(config);
};
