== AeroGear JavaScript Security SDK

AeroGear JavaScript SDK offers a set of security features that will make sure that your application is meeting the modern OWASP recomendations. All security features are available as part of the separate package `@aerogear/security`. This package offers multiple security checks that can be used to analyse the security of the device. This can be useful for developers to detect vulnerabilities and react accordingly. For example, if the app detects security issue *X* then do *Y*, where *X* could be no lock screen is set and *Y* is show a system prompt to setup the lock screen.

This package offers:

1. A suite of self-defence checks to detect a insecure or hostile environment.
2. Ability to implement custom self-defence checks.
3. Callbacks to access the results of self-defence checks and take appropriate action in application code.
4. Integration with the AeroGear Services Metrics SDK to report self-defence checks data.

=== Installation

1. Install the Security package, available via NPM:
+
----
npm install @aerogear/security
----

2. Add the AeroGear Security plugin for Cordova:
+
----
cordova plugin add cordova-plugin-aerogear-security
----

This will install the packages needed with their native dependencies from the NPM registry and properly link all native dependencies to the project's cordova Platforms.

=== Usage

To begin using the self defence checks in your app, you'll need to import `SecurityService` from `@aerogear/security`:

[source,javascript]
----
import { SecurityService } from '@aerogear/security';
----

You will also need to retrieve an instance of `SecurityService`:

[source,javascript]
----
const securityService = new SecurityService();
----

=== Provided Self Defence Checks

The following are the self defence checks provided by the SDK.

*Important* A successful `check` means that the environment the application is running in is more secure and no action is required, as opposed to signalling if a certain feature is enabled.

For example, the Root Access Detection check `notRooted` should return `true` when it is *not* rooted, since this would be the more secure condition.

==== Emulator Detection Check (notEmulated)

To detect if the app is being run on an emulator the `notEmulated` function can be used. If the device is *not* running in an emulator then the check will pass.

==== Root Access Detection Check (notRooted)

To help prevent your app running in a device that has been rooted/jailbroken the `notRooted` function can be used. If the device is *not* rooted/jailbroken then the check will pass.

==== Debug Mode Check (notDebugMode)

To detect if the app is runing in debug mode the `notDebugMode` function can be used. If the device is *not* running in debug mode then the check will pass.

==== Device Lock Check (hasDeviceLock)

To detect if a device has a lock screen set the `hasDeviceLock` function can be used. If the device *has* a screen lock enabled then this check will pass.

NOTE: For iOS devices this check requires iOS 8 or above.

=== Custom Self Defence Checks

Custom self defence checks can be used with the Security SDK. Custom self defence checks must implement the link:https://github.com/aerogear/aerogear-js-sdk/blob/master/packages/security/src/deviceTrust/SecurityCheck.ts[SecurityCheck] interface.

An example of a custom check structure in TypeScript:

[source,typescript]
----
class CustomSecurityCheck implements SecurityCheck {
    get name(): string {
        return "My Custom Check";
    }

    public check(): Promise<SecurityCheckResult> {
        // Perform check logic.
    }
}
----

=== Invoking a Single Self Defence Check

The `SecurityService.check` function is used to invoke a check which returns a promise of type `SecurityCheckResult`. The `check` function takes a paramater of type `SecurityCheckType` which will specify the type of check to be invoked:

[source,javascript]
----
securityService.check(SecurityCheckType.notEmulated).then((result) => {
    // -> add your logic to handle the result
})
----

=== Invoking Multiple Self Defence Checks

To chain multiple checks together the `SecurityService.checkMany` function is used. This returns an array of `SecurityCheckResult` objects in the order they`re provided in:

[source,javascript]
----
const checkResults = await securityService.checkMany(SecurityCheckType.notRooted, SecurityCheckType.notEmulated);
----

=== Reporting Self Defence Checks Results Via the Metrics Service

The results of security checks can be published to the AeroGear metrics service.

This functionality requires the cordova plugin @aerogear/cordova-plugin-aerogear-security to be installed.

To perform a single check and publish its result to the metrics service:

[source,javascript]
----
securityService.checkAndPublishMetric(SecurityCheckType.notRooted).then((result) => {
    // -> Handle the security result metric.
    // Security result metric structure: { id: 'isRooted', name: 'isRooted', passed: true }.
})
----

To perform multiple checks and publish their results to the metrics service:

[source,javascript]
----
securityService.checkManyAndPublishMetric(SecurityCheckType.notRooted, SecurityCheckType.notEmulated).then((result) => {
    // -> Handle the array of security result metrics
})
----
