== AeroGear JavaScript Auth SDK

Mobile authentication SDK based on link:http://www.keycloak.org/[Keycloak] using link:http://openid.net/connect/[OpenID Connect].

=== Prerequisites

1. To use the Auth SDK you'll first need to have a Keycloak instance. Follow the next steps to set it up using Openshift:

.. If you do not have mobile services enabled in your openshift cluster follow this link:https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/local-setup.adoc[Local Setup] guide.

.. Navigate to your Openshift cluster and in the Service Catalog search for the Keycloak service.

.. Click on the Keycloak service and you will be prompted to fill in details about your app.  For now you can leave these as they are.  Navigate through the setup and click Create.
This will provision the Keycloak service in the project you specified and create a public Client to be used with an app along with a bearer-only client.
See link:http://www.keycloak.org/docs/latest/server_admin/index.html#oidc-clients[Keycloak OIDC client documentation].

.. Specify the redirect URI as localhost:
+
`http://localhost/*`

2. Install the Auth package:
+
----
npm install @aerogear/auth
----

3. Generate again the app configuration file to use during xref:getting-started.adoc[app initialization]. For an example of Keycloak configuration see the example app's link:https://github.com/aerogear/cordova-showcase-template/blob/master/src/mobile-services.json[mobile-services.json].

=== Auth Service Initialization
Once the AeroGear SDK is initialized (see xref:getting-started.adoc[Getting Started]) you can import and initialize `Auth`:

[source,javascript]
----
import { Auth } from "@aerogear/auth";

const authService = new Auth();

const initOptions = { onLoad: "login-required" };
authService.init(initOptions)
    .then(() => {
        // successful init & authentication
    })
    .catch((err) => {
        // initialization error
    });
----

You can pass `login-required` or `check-sso` to the init function. `login-required` will authenticate the client if the user is logged-in to Keycloak or display the login page if not.
`check-sso` will only authenticate the client if the user is already logged-in, if the user is not logged-in the browser will be redirected back to the application and remain unauthenticated.

By default, the `check-sso` option is used. To enable the `login-required` action, simply pass it in the init function:

[source,javascript]
----
authService.init({ onLoad: "login-required" })
----

*Note*: Initialising the `Auth` will also perform the authentication action.

*Note*: In AngularJS, it is necessary to initialise the Auth SDK before bootstrapping Angular to prevent Redirect looping issues after authentication.
An example of how to perform this in Angular 4 is available in the Aerogear Cordova Showcase App's https://github.com/aerogear/cordova-showcase-template/blob/master/src/app/main.ts[main.ts].

=== Manual Authentication
To redirect to the login screen, invoke the `login` function:
[source,javascript]
----
authService.login()
----

=== Retrieving the Current User
To retrieve the current authenticated user the `loadUserProfile` function can be invoked. This will be `null` if there is no user authenticated. To check if a user is authenticated the `isAuthenticated` function can be invoked
[source,javascript]
----
if (this.auth.isAuthenticated()) {
    // user is authenticated, retrieve the profile
    this.auth.loadUserProfile().then((userProfile) => {
        // get username
        let username = userProfile.username;
        // get users first name
        let firstName = userProfile.firstName;
        // get users last name
        let lastName = userProfile.lastName;
        // get users Id
        let userId = userProfile.id;
        // get users email
        let email = userProfile.email;
    }).catch((err) => console.error("Error retrieving user profile", err));
} else {
    // not authenticated
}
----

=== Logging Out
To logout, invoke the `logout` function:

[source,javascript]
----
authService.logout()
----
By default, the local tokens obtained during authentication are only deleted when the logout succeeded against the authentication server.

*Note:* To perform backchannel or federated logouts, you must enable the Backchannel Logout option for the federated identity provider. More information is available in the Keycloak documentation under  http://www.keycloak.org/docs/latest/server_admin/index.html#openid-connect-v1-0-identity-providers[OIDC Identity Providers].
