= AeroGear Services Auth SDK

Mobile authentication SDK based on link:http://www.keycloak.org/[Keycloak] using link:http://openid.net/connect/[OpenID Connect].

== Usage

To use the Auth SDK you'll first need to:

* Have a Keycloak instance. See the <<Setting up Keycloak>> section.
* A configuration file added to the app directory. See the <<Configuration File>> section.

=== Setting up Keycloak

==== Using OpenShift

* If you do not have mobile services enabled in your openshift cluster follow this link:https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/local-setup.adoc[Local Setup] guide.
* Navigate to your Openshift cluster and in the Service Catalog search for the Keycloak service.
* Click on the Keycloak service and you will be prompted to fill in details about your app.  For now you can leave these as they are.  Navigate through the setup and click Create.
This will provision the Keycloak service in the project you specified and create a public Client to be used with an app along with a bearer-only client.
See link:http://www.keycloak.org/docs/latest/server_admin/index.html#oidc-clients[Keycloak OIDC client documentation].


==== Specifying the Redirect URI
For Cordova based applications, localhost can be specified as a redirect URI in the Keycloak client when using an in-app browser:

 * `http://localhost/*`

=== Adding Auth Package
Add the Auth package with NPM:
----
npm install aerogear/auth@latest --save
----

=== Configuration File

A `mobile-services.json` file must exist in the app directory. It should specify configuration
for Keycloak. This configuration can be generated by the link:https://github.com/aerogear/mobile-cli[AeroGear Mobile CLI].

For an example of Keycloak configuration see the example apps link:../../example/cordova/www/mobile-services.json[mobile-services.json].

The Auth SDK will use this configuration to communicate with Keycloak.

=== Auth Service Initialization
The `Auth` can be retrieved by importing it. The `mobile-services.json` file must also be referenced as it contains the Keycloak configuration.
----
import { Auth } from '@aerogear/auth';
import { init } from '@aerogear/app';

let mobileServiceConfig = require("../mobile-services.json");
init(mobileServiceConfig);
----
Before the `Auth` can be used, the `init` function must be invoked once in an app.

----
let authService = new Auth();

let initOptions = {onLoad: "login-required"};
authService.init(initOptions)
    .then(() => {
        // successful init & authentication
    })
    .catch((err) => {
        // initialization error
    });
----

You can pass `login-required` or `check-sso` to the init function. `login-required` will authenticate the client if the user is logged-in to Keycloak or display the login page if not.
`check-sso` will only authenticate the client if the user is already logged-in, if the user is not logged-in the browser will be redirected back to the application and remain unauthenticated.

By default, the `check-sso` option is used. To enable the `login-required` action, simply pass it in the init function:

```
authService.init({onLoad: "login-required"})
```

*Note*: Initialising the `Auth` will also perform the authentication action.

*Note*: In AngularJS, it is necessary to initialise the Auth SDK before bootstrapping Angular to prevent Redirect looping issues after authentication.
An example of how to perform this in Angular 4 is available in the Aerogear Cordova Showcase App's https://github.com/aerogear/cordova-showcase-template/blob/master/src/app/main.ts[main.ts].

=== Manual Authentication
To redirect to the login screen, invoke the `login` function:
----
authService.login()
----

=== Retrieving the Current User
To retrieve the current authenticated user the `loadUserProfile` function can be invoked. This will be `null` if there is no user authenticated. To check if a user is authenticated the `isAuthenticated` function can be invoked
----
if (this.auth.isAuthenticated()) {
    // user is authenticated, retrieve the profile
    this.auth.loadUserProfile().then((userProfile) => {
      // get username
      let username = userProfile.username;
      // get users first name
      let firstName = userProfile.firstName;
      // get users last name
      let lastName = userProfile.lastName;
      // get users Id
      let userId = userProfile.id;
      // get users email
      let email = userProfile.email;
    }).catch((err) => console.error("Error retrieving user profile", err));
} else {
    // not authenticated
}
----

=== Logging Out
To logout, invoke the `logout` function:
----
authService.logout()
----
By default, the local tokens obtained during authentication are only deleted when the logout succeeded against the authentication server.

*Note:* To perform backchannel or federated logouts, you must enable the Backchannel Logout option for the federated identity provider. More information is available in the Keycloak documentation under  http://www.keycloak.org/docs/latest/server_admin/index.html#openid-connect-v1-0-identity-providers[OIDC Identity Providers].
