/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ApolloOfflineClientConfigIntf = t.iface(["ApolloOfflineClientOptions"], {
  "httpUrl": t.opt("string"),
  "offlineQueueListener": t.opt("ApolloOfflineQueueListener"),
  "conflictStrategy": "ConflictResolutionStrategy",
  "conflictProvider": "ObjectState",
  "networkStatus": t.opt("NetworkStatus"),
  "terminatingLink": t.union("ApolloLink", "undefined"),
  "cacheStorage": "PersistentStore",
  "offlineStorage": "PersistentStore",
  "conflictListener": "CompositeConflictListener",
  "mutationCacheUpdates": t.opt("CacheUpdates"),
  "cachePersistor": t.opt("CachePersistor"),
  "link": t.opt("ApolloLink"),
  "inputMapper": t.opt("InputMapper"),
  "cache": "any",
});

const exportedTypeSuite: t.ITypeSuite = {
  ApolloOfflineClientConfigIntf,
};
export default exportedTypeSuite;
