= AeroGear Core SDK

The Core SDK provides helpers for parsing the configuration file and share common utilities between other SDK modules.

It's main features are:

* Parsing of the configuration file
* Metrics gathering

== Installation

The `@aerogear/core` module is available via NPM:

----
npm install @aerogear/core
----

=== Additional steps for a Cordova project

After node module installation via NPM use the Cordova CLI to add the additional native dependencies to your project:

----
cordova plugin add @aerogear/cordova-plugin-aerogear-metrics
----

This will install the packages with these native dependencies from the NPM registry and properly link all native dependencies to the project's cordova Platforms.

Refer to the link:../modules/ROOT/pages/getting-started.adoc[Getting Started] guide for more information on installing the AeroGear SDK.

== Usage

The Core module is used in app module that supports parsing of the configuration file generated by the mobile CLI, in practice this feature is used internally by other modules of the SDK:

[source, javascript]
----
import { AeroGearApp } from '@aerogear/app';

const metricsConfig = new AeroGearApp(config).getConfigByType(MetricsService.TYPE);
----

