== Getting Started with AeroGear JavaScript SDK

This guide provides general information for creating applications that utilize the AeroGear JavaScript SDK.

== Prerequisites for Apache Cordova

In order to develop a Cordova application utilizing the SDK you will need the following prerequisites installed:

 * The link:https://nodejs.org/en/download/[Node.js] runtime and NPM
 * https://github.com/aerogear/mobile-cli[AeroGear Mobile CLI]
 * Apache link:https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli[Cordova CLI]

== Installing the AeroGear JavaScript SDK

The services in the SDK are available as NPM packages under the `@aerogear` org. In order to use them in your application simply run:
[source.bash]
npm install @aerogear/<module>

== Adding the AeroGear Services Configuration file

In order to use any module, a AeroGear specific configuration file called `mobile-services.json` is needed. Utilize the https://github.com/aerogear/mobile-cli[AeroGear Mobile CLI] to generate a it and place it inside your root directory.

For a Cordova project, it should be placed in `www/mobile-services.json`.

////
=== Including native plugins on your Cordova project

TODO: to be finished when we integrate plugins in the SDK (metrics) 

////
