= AeroGear Services Metrics SDK

Metrics is another service provided by Core and no further dependencies are required for its utilization.
It provides registration of default metrics for the application such as App and Device information as well as supplying these services to other modules of the SDK.

== Usage
With an instance of the `MetricsService` class, it is possible to send a set of default metrics to an https://github.com/aerogear/aerogear-app-metrics[Aerogear App Metrics] instance.

[source, javascript]
----
import { Metrics, MetricsService } from '@aerogear/core';
import configuration from '../mobile-services.json';

const metrics = new MetricsService(configuration);

metrics.sendAppAndDeviceMetrics()
  .then(() => {
    console.info("Metrics registered successfully");
  });
----

== Default metrics

They are composed by the following fields:

App metrics::
- *App version*: The version of your App
- *SDK version*: The version of the Aerogear JS SDK that is used

Device metrics::
- *Platform*: The `cordova-` prefix along with the native platform being run on
- *Platform Version*: The runtime version of your chosen platform