== Getting Started with the AeroGear JavaScript SDK

This document provides a comprehensive guide to integrate and use the Aerogear SDK on your Cordova project.

=== Prerequisites

Before installing the SDK you will need in your system, at least:

* link:https://nodejs.org/[Node.js] runtime and NPM
* link:https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli[Cordova CLI]

=== Add AeroGear SDK

1. Get your app's configuration from the link:https://github.com/aerogear/mobile-cli[AeroGear Mobile CLI]. This JSON file contains custom confguration data for your project and shouldn't be changed manually. Every time a new service is provisioned the file has to be replaced by a new one.

2. Install the AeroGear SDK base project "app" in your Javascript project, which is available on NPM under the @aerogear org. Run the following command on your terminal:
+
[source.bash]
npm install @aerogear/app
+
This package provides a way to initialize and prepare the client in order to use the SDK, based on the configuration file that has been generated. In your application, import and call the "init" method:
+
```
import { init } from "@aerogear/app";

const appConfig = {
    // Replace with your own configuration
};

init(appConfig);
```
+
Once this method is called, the whole SDK will be ready to use.

=== Adding more services to the SDK

You can now use any of the services that AeroGear provides, some of them require additional dependencies and steps:

** xref:metrics.adoc[Metrics]
** xref:auth.adoc[Auth]
** xref:security-checks.adoc[Push]
